export const defaultValues = [
  {
    name: 'ping-cycle',
    displayName: 'Ping Cycle',
    image: './assets/purple.png',
    cost: 16,
    increase: 1,
    cpMultiplier: 1.025,
    costMultiplier: 1.12,
  },
  {
    name: 'low-power-processing',
    displayName: 'Low-Power<br>Processing',
    image: './assets/blue.png',
    cost: 128,
    increase: 4,
    cpMultiplier: 1.03,
    costMultiplier: 1.115,
  },
  {
    name: 'mid-power-processing',
    displayName: 'Mid-Power<br>Processing',
    image: './assets/green.png',
    cost: 1024,
    increase: 16,
    cpMultiplier: 1.035,
    costMultiplier: 1.11,
  },
  {
    name: 'high-power-processing',
    displayName: 'High-Power<br>Processing',
    image: './assets/gold.png',
    cost: 8192,
    increase: 128,
    cpMultiplier: 1.04,
    costMultiplier: 1.1,
  },
];
